### ISSUE TITLE
go not found

### ISSUE THREAD

**Issue by gedw99** [primatejs/app#8]
```sh
npm start

> @primate/app@0.30.0 start
> npx primate

primate 0.30.1 in startup
-- primate running init hooks 
-- primate/store loading Post User ns.Post 
-- primate/store all stores nominal 
-- primate/i18n loading de-DE de en-US en 
-- primate/i18n all locales nominal 
-- primate running stage hooks 
!! primate/binding/go the Go route go/index.go contains the following error
 /bin/sh: go: command not found
 
++ fix the Go error
   -> https://primatejs.com/modules/primate/binding/go#error-in-go-route 
ErrorInGoRoute: the Go route go/index.go contains the following error
 /bin/sh: go: command not found

    at Object.new (file:///Users/apple/primate/app/node_modules/primate/src/Logger.js:31:19)
    at Object.throw (file:///Users/apple/primate/app/node_modules/primate/src/Logger.js:39:19)
    at Object.route (file:///Users/apple/primate/app/node_modules/@primate/binding/src/bindings/go/module.js:181:40)
    at async post (file:///Users/apple/primate/app/node_modules/primate/src/hooks/stage.js:37:5) {
  level: 0,
  fix: 'fix the Go error',
  module: 'primate/binding/go'
}
~~ bye
apple@apples-MBP primate % which go
/opt/homebrew/opt/go/libexec/bin/go
```

**Comment by terrablue** [comment]
Hey, thanks for the report.

Is it generally erroneous to execute Go via node?

```js
import { exec } from "node:child_process";

exec("go version", (error, stdout, stderr) => {
  console.log(error === null ? stdout : stderr);
});
```

Could you try running this with node? This is more or less what Primate does. It should probably result in the same error. What shell are you using?

**Comment by terrablue** [comment]
I'm not entirely sure what the issue is. I installed Go on a Mac with `brew install go`, and `which go` shows `/usr/local/bin/go`. Creating a Go route seems to be working, as well as the example I posted in the last comment.

Are you doing anything differently in terms of installing Go?

**Comment by gedw99** [comment]
It’s me :) I had 2 Golangs installed.
